name: Deploy Docker Image to Servers

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t stuped-image:latest .

    # Login to Docker Registry
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push the Docker image
    - name: Push Docker Image
      run: |
        docker tag stuped-image:latest renatojrksx/stuped-image:latest
        docker push renatojrksx/stuped-image:latest

    # Deploy to multiple servers
    - name: Deploy to Servers
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOSTS }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull renatojrksx/stuped-image:latest
          docker stop estuped-app || true
          docker run -d --name estuped-app  renatojrksx/stuped-image:latest
